import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getData = async () => {
  const res = await fetch(
    "https://mocki.io/v1/6ca5a578-1e11-4436-af72-204764ddd7f2"
  );
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  // Recommendation: handle errors
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getData();
  return (
    <html lang="en">
      <body>
        <header>This is a header {JSON.stringify(data)}</header>
        {children}
      </body>
    </html>
  );
}
